remote_theme: "dracula/gh-pages"
title: Evan Barclay Resume
description: if your looking for a download head over to the <a href="https://github.com/BagpipesRbetter/Resume">Github</a>
include:
  - style.css
